### ISSUE TITLE
Provide Integration Instructions for Starter Frontend

### ISSUE THREAD

**Issue by jarednorman** [friendlycart/solidus_friendly_promotions#90]
I installed this on a new store using the starter frontend and found that out of the box the promotions I was creating weren't working when I put the coupon code in on the cart page. This was because the `CouponCodesController` references the stock `Solidus::PromotionHandler::Coupon`. Swapping it out for `SolidusFriendlyPromotions::PromotionHandler::Coupon` fixes the issue.

I'm not sure if there are other touchpoints that need to be handled, but we should probably document at least this touchpoint.

**Comment by mamhoff** [comment]
I'll get to that shortly, for now there's a PR to `solidus_starter_frontend` to make this not an issue by default for new stores.
